"""Bounded, non-claim docking proposal, authority, placement, contact, scoring, and search contracts."""

from .identity import (
    DockingIdentityError,
    DockingProblemIdentity,
    coordinate_fingerprint,
    search_space_fingerprint,
)
from .metrics import (
    MAX_SYMMETRY_PERMUTATIONS,
    PoseMetricError,
    RMSDResult,
    direct_rmsd,
    kabsch_aligned_coordinates,
    kabsch_aligned_rmsd,
    symmetry_aware_rmsd,
)
from .proposals import (
    MAX_DOCKING_CANDIDATES,
    MAX_DOCKING_REFINEMENT_STEPS,
    MAX_DOCKING_TOP_K,
    MAX_DOCKING_TORSIONS,
    DockingBudget,
    DockingProposal,
    DockingProposalError,
    TorsionSearchSpace,
    generate_bounded_docking_proposals,
)
from .scoring import (
    DockingScoreDescriptor,
    ScoreDirection,
    UNCALIBRATED_INTERNAL_DOCKING_SCORE,
    component_contract_fingerprint,
    component_problem_fingerprint,
    scorer_descriptor,
)
from .search import (
    DockingPoseRefiner,
    DockingPoseScorer,
    DockingSearchError,
    DockingSearchResult,
    DockingSearchRow,
    run_bounded_docking_search,
)
from .validity import (
    PoseValidityConfig,
    PoseValidityContext,
    PoseValidityError,
    PoseValidityResult,
    evaluate_pose_validity,
)
from .authority import (
    AUTHENTICATED_DOCKING_DERIVATION_ID,
    AUTHENTICATED_DOCKING_DERIVATION_POLICY_SCHEMA_ID,
    AUTHENTICATED_DOCKING_INPUT_SCHEMA_ID,
    AUTHENTICATED_DOCKING_MAX_LIGAND_ATOMS,
    AUTHENTICATED_DOCKING_MAX_LIGAND_BONDS,
    AUTHENTICATED_DOCKING_MAX_POCKET_RADIUS_ANGSTROM,
    AUTHENTICATED_DOCKING_MAX_RECEPTOR_ATOMS,
    AUTHENTICATED_DOCKING_MAX_RECEPTOR_MARGIN_ANGSTROM,
    AUTHENTICATED_DOCKING_SEARCH_RESULT_SCHEMA_ID,
    AuthenticatedDockingProblem,
    AuthenticatedDockingSearchResult,
    DockingAuthorityError,
    DockingScope,
    PocketDefinition,
    TorsionSearchSpaceDerivationReceipt,
    authenticated_docking_derivation_policy_document,
    build_authenticated_known_pocket_docking_problem,
    derive_authoritative_torsion_search_space,
    run_authenticated_bounded_docking_search,
)
from .authority_rotor_compat import (
    install_authority_rotor_stereo_compat as _install_authority_rotor_stereo_compat,
)

AUTHORITY_ROTOR_STEREO_COMPAT_SHA256 = (
    _install_authority_rotor_stereo_compat()
)

# Rebind the public functions after the compatibility installer updates authority.
from .authority import (
    derive_authoritative_torsion_search_space,
    run_authenticated_bounded_docking_search,
)
from .placement import (
    CENTROID_POLICY_ID,
    COUNTER_PRNG_ID,
    HAAR_ROTATION_SAMPLER_ID,
    MAX_POCKET_PLACEMENT_PROPOSALS,
    MAX_POCKET_TRANSLATION_RADIUS_ANGSTROM,
    POCKET_PLACEMENT_POLICY_ID,
    POCKET_PLACEMENT_POLICY_SCHEMA_ID,
    POCKET_PLACEMENT_RECEIPT_SCHEMA_ID,
    POCKET_PLACEMENT_SEARCH_RESULT_SCHEMA_ID,
    SPHERICAL_TRANSLATION_SAMPLER_ID,
    PocketPlacementPolicy,
    PocketPlacementReceipt,
    PocketPlacementSearchResult,
    generate_pocket_centered_docking_proposals,
    install_pocket_proposal_override as _install_pocket_proposal_override,
    run_authenticated_pocket_placement_search,
)

POCKET_PROPOSAL_OVERRIDE_SHA256 = _install_pocket_proposal_override()

from .contact_validity import (
    ELEMENT_AWARE_AUTHORITY_SCHEMA_ID,
    ELEMENT_AWARE_VALIDITY_CONTEXT_SCHEMA_ID,
    MAX_ELEMENT_AWARE_LIGAND_ATOMS,
    MAX_ELEMENT_AWARE_LIGAND_PAIR_CHECKS,
    MAX_ELEMENT_AWARE_RECEPTOR_ATOMS,
    MAX_ELEMENT_AWARE_RECEPTOR_CANDIDATE_PAIRS,
    SPARSE_CONTACT_ALGORITHM_ID,
    VDW_CONTACT_POLICY_ID,
    VDW_CONTACT_POLICY_SCHEMA_ID,
    VDW_RADII_TABLE_ID,
    ElementAwarePoseValidityContext,
    ElementAwareValidityError,
    VdwContactPolicy,
    build_element_aware_authenticated_known_pocket_docking_problem,
    element_aware_authority_document,
)
from .interpretable_scorer import (
    INTERPRETABLE_POSE_APPLICABILITY_DOMAIN_ID,
    INTERPRETABLE_POSE_SCORE_ALGORITHM_ID,
    INTERPRETABLE_POSE_SCORE_CONFIG_SCHEMA_ID,
    INTERPRETABLE_POSE_SCORE_ID,
    INTERPRETABLE_POSE_SCORE_TERMS_SCHEMA_ID,
    INTERPRETABLE_POSE_SCORER_ID,
    INTERPRETABLE_POSE_SCORER_VERSION,
    MAX_INTERPRETABLE_SCORER_LIGAND_PAIR_CHECKS,
    MAX_INTERPRETABLE_SCORER_RECEPTOR_CANDIDATE_PAIRS,
    InterpretablePoseScoreConfig,
    InterpretablePoseScoreTerms,
    InterpretablePoseScorerError,
    InterpretablePoseScorerV0,
)

__all__ = [
    "AUTHENTICATED_DOCKING_DERIVATION_ID",
    "AUTHENTICATED_DOCKING_DERIVATION_POLICY_SCHEMA_ID",
    "AUTHENTICATED_DOCKING_INPUT_SCHEMA_ID",
    "AUTHENTICATED_DOCKING_MAX_LIGAND_ATOMS",
    "AUTHENTICATED_DOCKING_MAX_LIGAND_BONDS",
    "AUTHENTICATED_DOCKING_MAX_POCKET_RADIUS_ANGSTROM",
    "AUTHENTICATED_DOCKING_MAX_RECEPTOR_ATOMS",
    "AUTHENTICATED_DOCKING_MAX_RECEPTOR_MARGIN_ANGSTROM",
    "AUTHENTICATED_DOCKING_SEARCH_RESULT_SCHEMA_ID",
    "AUTHORITY_ROTOR_STEREO_COMPAT_SHA256",
    "CENTROID_POLICY_ID",
    "COUNTER_PRNG_ID",
    "ELEMENT_AWARE_AUTHORITY_SCHEMA_ID",
    "ELEMENT_AWARE_VALIDITY_CONTEXT_SCHEMA_ID",
    "HAAR_ROTATION_SAMPLER_ID",
    "INTERPRETABLE_POSE_APPLICABILITY_DOMAIN_ID",
    "INTERPRETABLE_POSE_SCORE_ALGORITHM_ID",
    "INTERPRETABLE_POSE_SCORE_CONFIG_SCHEMA_ID",
    "INTERPRETABLE_POSE_SCORE_ID",
    "INTERPRETABLE_POSE_SCORE_TERMS_SCHEMA_ID",
    "INTERPRETABLE_POSE_SCORER_ID",
    "INTERPRETABLE_POSE_SCORER_VERSION",
    "MAX_DOCKING_CANDIDATES",
    "MAX_DOCKING_REFINEMENT_STEPS",
    "MAX_DOCKING_TOP_K",
    "MAX_DOCKING_TORSIONS",
    "MAX_ELEMENT_AWARE_LIGAND_ATOMS",
    "MAX_ELEMENT_AWARE_LIGAND_PAIR_CHECKS",
    "MAX_ELEMENT_AWARE_RECEPTOR_ATOMS",
    "MAX_ELEMENT_AWARE_RECEPTOR_CANDIDATE_PAIRS",
    "MAX_INTERPRETABLE_SCORER_LIGAND_PAIR_CHECKS",
    "MAX_INTERPRETABLE_SCORER_RECEPTOR_CANDIDATE_PAIRS",
    "MAX_POCKET_PLACEMENT_PROPOSALS",
    "MAX_POCKET_TRANSLATION_RADIUS_ANGSTROM",
    "MAX_SYMMETRY_PERMUTATIONS",
    "POCKET_PLACEMENT_POLICY_ID",
    "POCKET_PLACEMENT_POLICY_SCHEMA_ID",
    "POCKET_PLACEMENT_RECEIPT_SCHEMA_ID",
    "POCKET_PLACEMENT_SEARCH_RESULT_SCHEMA_ID",
    "POCKET_PROPOSAL_OVERRIDE_SHA256",
    "SPARSE_CONTACT_ALGORITHM_ID",
    "SPHERICAL_TRANSLATION_SAMPLER_ID",
    "VDW_CONTACT_POLICY_ID",
    "VDW_CONTACT_POLICY_SCHEMA_ID",
    "VDW_RADII_TABLE_ID",
    "AuthenticatedDockingProblem",
    "AuthenticatedDockingSearchResult",
    "DockingAuthorityError",
    "DockingBudget",
    "DockingIdentityError",
    "DockingPoseRefiner",
    "DockingPoseScorer",
    "DockingProblemIdentity",
    "DockingProposal",
    "DockingProposalError",
    "DockingScope",
    "DockingScoreDescriptor",
    "DockingSearchError",
    "DockingSearchResult",
    "DockingSearchRow",
    "ElementAwarePoseValidityContext",
    "ElementAwareValidityError",
    "InterpretablePoseScoreConfig",
    "InterpretablePoseScoreTerms",
    "InterpretablePoseScorerError",
    "InterpretablePoseScorerV0",
    "PocketDefinition",
    "PocketPlacementPolicy",
    "PocketPlacementReceipt",
    "PocketPlacementSearchResult",
    "PoseMetricError",
    "PoseValidityConfig",
    "PoseValidityContext",
    "PoseValidityError",
    "PoseValidityResult",
    "RMSDResult",
    "ScoreDirection",
    "TorsionSearchSpace",
    "TorsionSearchSpaceDerivationReceipt",
    "UNCALIBRATED_INTERNAL_DOCKING_SCORE",
    "VdwContactPolicy",
    "authenticated_docking_derivation_policy_document",
    "build_authenticated_known_pocket_docking_problem",
    "build_element_aware_authenticated_known_pocket_docking_problem",
    "component_contract_fingerprint",
    "component_problem_fingerprint",
    "coordinate_fingerprint",
    "derive_authoritative_torsion_search_space",
    "direct_rmsd",
    "element_aware_authority_document",
    "evaluate_pose_validity",
    "generate_bounded_docking_proposals",
    "generate_pocket_centered_docking_proposals",
    "kabsch_aligned_coordinates",
    "kabsch_aligned_rmsd",
    "run_authenticated_bounded_docking_search",
    "run_authenticated_pocket_placement_search",
    "run_bounded_docking_search",
    "scorer_descriptor",
    "search_space_fingerprint",
    "symmetry_aware_rmsd",
]
