[package]
name = "betelgeuze-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish = false

[features]
default = []
hip = ["betelgeuze-sys/hip"]

[dependencies]
betelgeuze-sys = { version = "0.1.0", path = "../betelgeuze-sys" }
sha2 = "=0.10.9"

[dev-dependencies]
betelgeuze-reference-dynamics = { version = "0.1.0", path = "../reference-dynamics" }
betelgeuze-reference-physics = { version = "0.1.0", path = "../reference-physics" }
