#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from tools.builder_table_utils import write_csv_rows

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_JSON = "runs/goal_api_surface_contract_current.json"
DEFAULT_OUT_CSV = "runs/goal_api_surface_contract_current.csv"
DEFAULT_OUT_MD = "runs/goal_api_surface_contract_current.md"

CLAIM_BOUNDARY = (
    "Goal API surface contract only; it statically audits the read-only local goal API for commercial product, "
    "CAMEO validation, CASP17 transition, and cleanup status. It does not start a server, run docking, install "
    "packages, submit predictions, register servers, send email, delete, archive, externalize, upload, or mutate "
    "external state."
)

EXPECTED_ENDPOINTS = {
    "/status": "get_goal_status",
    "/readiness": "get_goal_readiness",
    "/priority-queue": "get_goal_priority_queue",
    "/developer-preview": "get_goal_developer_preview",
    "/public-benchmark": "get_goal_public_benchmark",
    "/customer-shadow": "get_goal_customer_shadow",
    "/api-customer-flow": "get_goal_api_customer_flow",
    "/actions": "get_goal_actions",
    "/operator-intake-kit": "get_goal_operator_intake_kit",
    "/release-decision": "get_goal_release_decision",
    "/burndown": "get_goal_burndown",
    "/bottlenecks": "get_goal_bottlenecks",
    "/api-contract": "get_goal_api_contract",
}

EXPECTED_ARTIFACT_CONSTANTS = {
    "GOAL_READINESS_ROLLUP_ARTIFACT",
    "PM_PRIORITY_QUEUE_ARTIFACT",
    "DEVELOPER_PREVIEW_FINAL_GATE_AUDIT_ARTIFACT",
    "PUBLIC_BENCHMARK_EXTERNAL_RECEIPTS_AUDIT_ARTIFACT",
    "PUBLIC_BENCHMARK_RECEIPT_ATTACH_PACKET_ARTIFACT",
    "CUSTOMER_SHADOW_EVIDENCE_STATUS_ARTIFACT",
    "API_CUSTOMER_FLOW_RELEASE_EVIDENCE_ARTIFACT",
    "GOAL_OPERATOR_ACTION_BOARD_ARTIFACT",
    "GOAL_OPERATOR_INTAKE_KIT_MANIFEST",
    "GOAL_RELEASE_DECISION_ARTIFACT",
    "GOAL_RELEASE_BURNDOWN_ARTIFACT",
    "GOAL_BOTTLENECK_BRIEFING_ARTIFACT",
    "GOAL_API_SURFACE_CONTRACT_ARTIFACT",
    "PRODUCT_GOAL_COMPLETION_AUDIT_ARTIFACT",
    "PRODUCT_COMMERCIAL_READINESS_HANDOFF_BUNDLE_ARTIFACT",
    "PRODUCT_RELEASE_BUNDLE_ARTIFACT",
    "PRODUCT_SCOPE_BREADTH_EVIDENCE_PRIORITY_PACKET_ARTIFACT",
    "ENGINE_REFINEMENT_CLAIM_EVIDENCE_PRIORITY_PACKET_ARTIFACT",
    "PRODUCT_FULL_COMMERCIAL_BLOCKER_EVIDENCE_MATRIX_ARTIFACT",
    "PRODUCT_SCOPE_BREADTH_EVIDENCE_RECEIPT_ARTIFACT",
    "ENGINE_REFINEMENT_CLAIM_EVIDENCE_RECEIPT_ARTIFACT",
    "CAMEO_OFFICIAL_RESULT_FETCH_PREFLIGHT_ARTIFACT",
    "PRODUCT_ROLLOUT_EXECUTION_SMOKE_RECEIPT_ARTIFACT",
    "PRODUCT_LAUNCH_R4_PREFLIGHT_ARTIFACT",
    "DEPLOY_OPS_LEGAL_GAP_CLOSURE_ARTIFACT",
}

REQUIRED_FULL_COMMERCIAL_VISIBILITY_TOKENS = {
    "FULL_COMMERCIAL_RELEASE_BLOCKER_IDS",
    "R8_full_scope_claim_closure",
    "R9_engine_refinement_claim_promotion",
    "ACCURACY:ligand_ranking",
    "full_commercial_release_blocker_visibility_ready",
    "missing_full_commercial_release_blocker_ids",
    "operator_action_board_full_commercial_release_blocker_ids",
    "operator_intake_kit_full_commercial_release_blocker_ids",
    "bottleneck_briefing_full_commercial_release_blocker_ids",
    "full_commercial_release_blocker_downstream_visibility_ready",
    "full_commercial_release_blocker_downstream_missing_surfaces",
    "restricted_release_allowed",
    "full_commercial_release_allowed",
    "primary_full_commercial_release_blocker_id",
    "primary_full_commercial_release_blocker_requirement_id",
    "primary_full_commercial_release_blocker_tier",
    "primary_full_commercial_release_blocker",
    "primary_full_commercial_release_blocker_blocked_row_count",
    "primary_full_commercial_release_blocker_first_blocked_evidence_row_id",
    "primary_full_commercial_release_blocker_receipt_csv",
    "primary_full_commercial_release_blocker_approval_token_required",
    "primary_full_commercial_release_blocker_next_required_step",
    "full_commercial_release_next_required_step",
    "product_goal_primary_release_blocker_requirement_id",
    "primary_release_blocker_action_required_input",
    "close_ligand_ranking_claim_scope",
    "product_accuracy_parity_ligand_ranking_action_present",
    "FULL_COMMERCIAL_EVIDENCE_RECEIPT_STATUS_KEYS",
    "product_scope_breadth_evidence_receipt_status",
    "engine_refinement_claim_evidence_receipt_status",
    "product_scope_breadth_evidence_priority_status",
    "engine_refinement_claim_evidence_priority_status",
    "engine_refinement_priority_metric_source_payload_receipt_csv",
    "engine_refinement_priority_metric_source_payload_receipt_approval_token_required",
    "engine_refinement_priority_metric_source_payload_receipt_blocked_row_count",
    "engine_refinement_claim_evidence_priority_top_required_input",
}

REQUIRED_STATUS_KEYS = {
    "product_cli_status_set_status",
    "cameo_cli_status_set_status",
    "cleanup_cli_status_set_status",
    "approval_tokens",
    "approval_reclaim_size_gb",
    "protected_cleanup_payload_size_gb",
    "product_operational_quality_ready",
    "product_operational_quality_status",
    "product_operational_quality_blocker_count",
    "product_operational_quality_artifact",
    "cameo_evidence_integrity_ready",
    "cameo_evidence_integrity_status",
    "cameo_evidence_integrity_blocker_count",
    "cameo_evidence_integrity_artifact",
    "cameo_official_results_pending_honest",
    "cameo_no_local_native_accuracy_substitution",
    "release_allowed",
    "restricted_release_allowed",
    "full_commercial_release_allowed",
    "release_blocker_count",
    "bottleneck_count",
    "primary_bottleneck_kind",
    "primary_bottleneck_phase",
    "primary_bottleneck_root_cause_category",
    "primary_bottleneck_locally_closable_without_operator_return",
    "primary_bottleneck_required_external_return",
    "primary_bottleneck_post_return_acceptance_artifact",
    "completion_audit_release_blocker_bottleneck_count",
    "irreducible_external_return_bottleneck_count",
    "expected_full_commercial_release_blocker_ids",
    "full_commercial_release_blocker_ids",
    "full_commercial_release_blocker_count",
    "missing_full_commercial_release_blocker_ids",
    "full_commercial_release_blocker_visibility_ready",
    "operator_action_board_full_commercial_release_blocker_ids",
    "operator_action_board_full_commercial_release_blocker_count",
    "operator_intake_kit_full_commercial_release_blocker_ids",
    "operator_intake_kit_full_commercial_release_blocker_count",
    "bottleneck_briefing_full_commercial_release_blocker_ids",
    "bottleneck_briefing_full_commercial_release_blocker_count",
    "full_commercial_release_blocker_downstream_visibility_ready",
    "full_commercial_release_blocker_downstream_missing_surfaces",
    "primary_full_commercial_release_blocker_id",
    "primary_full_commercial_release_blocker_requirement_id",
    "primary_full_commercial_release_blocker_tier",
    "primary_full_commercial_release_blocker",
    "primary_full_commercial_release_blocker_blocked_row_count",
    "primary_full_commercial_release_blocker_first_blocked_evidence_row_id",
    "primary_full_commercial_release_blocker_receipt_csv",
    "primary_full_commercial_release_blocker_approval_token_required",
    "primary_full_commercial_release_blocker_next_required_step",
    "full_commercial_release_next_required_step",
    "master_gap_closure_rollup_status",
    "master_gap_closure_rollup_recorded",
    "master_gap_closure_rollup_all_gaps_closed",
    "master_gap_closure_rollup_claim_promotion_allowed",
    "master_gap_closure_rollup_open_gap_count",
    "master_gap_closure_rollup_open_gap_ids",
    "master_gap_closure_rollup_closed_gap_count",
    "master_gap_closure_rollup_closed_gap_ids",
    "master_gap_closure_rollup_release_blocker_row_count",
    "master_gap_closure_rollup_current_primary_open_gap_id",
    "master_gap_closure_rollup_science_claim_rollup_status",
    "master_gap_closure_rollup_science_claim_evidence",
    "master_gap_closure_rollup_science_claim_release_blocker",
    "science_claim_promotion_gap_closure_status",
    "science_claim_promotion_gap_closure_recorded",
    "science_claim_promotion_gap_closure_all_gaps_closed",
    "science_claim_promotion_gap_closure_claim_promotion_allowed",
    "science_claim_promotion_gap_closure_open_gap_count",
    "science_claim_promotion_gap_closure_open_gap_ids",
    "science_claim_promotion_gap_closure_closed_gap_count",
    "science_claim_promotion_gap_closure_closed_gap_ids",
    "science_claim_promotion_gap_closure_release_blocker_row_count",
    "science_claim_promotion_gap_closure_current_primary_open_gap_id",
    "science_claim_promotion_gap_closure_current_next_action",
    "science_claim_promotion_gap_closure_primary_open_gap_area",
    "science_claim_promotion_gap_closure_primary_open_gap_claim_promotion_status",
    "science_claim_promotion_gap_closure_primary_open_gap_evidence",
    "science_claim_promotion_gap_closure_primary_open_gap_next_action",
    "science_claim_promotion_gap_closure_primary_open_gap_release_blocker",
    "science_claim_promotion_gap_closure_gpcr_claim_promotion_status",
    "science_claim_promotion_gap_closure_gpcr_evidence",
    "science_claim_promotion_gap_closure_gpcr_release_blocker",
    "science_claim_promotion_gap_closure_openmm_claim_promotion_status",
    "science_claim_promotion_gap_closure_openmm_evidence",
    "science_claim_promotion_gap_closure_openmm_release_blocker",
    "accuracy_parity_scorecard_gate_present",
    "accuracy_parity_scorecard_status",
    "accuracy_parity_scorecard_recorded",
    "accuracy_parity_scorecard_row_count",
    "accuracy_parity_scorecard_pass_row_count",
    "accuracy_parity_scorecard_restricted_pass_row_count",
    "accuracy_parity_scorecard_blocked_row_count",
    "accuracy_parity_scorecard_missing_row_count",
    "accuracy_parity_scorecard_top_blocker_count",
    "accuracy_parity_scorecard_top_blockers",
    "accuracy_parity_scorecard_overall_commercial_tool_accuracy_parity_allowed",
    "accuracy_parity_scorecard_schrodinger_class_claim_allowed",
    "accuracy_parity_scorecard_openmm_class_claim_allowed",
    "accuracy_parity_scorecard_current_broad_accuracy_parity_estimate_pct",
    "accuracy_parity_scorecard_current_broad_commercial_platform_estimate_pct",
    "accuracy_parity_ligand_ranking_status",
    "accuracy_parity_ligand_ranking_claim_promotion_allowed",
    "accuracy_parity_ligand_ranking_commercial_parity_claim_allowed",
    "accuracy_parity_ligand_ranking_blocker_count",
    "accuracy_parity_ligand_ranking_blockers",
    "accuracy_parity_ligand_ranking_pr_auc",
    "accuracy_parity_ligand_ranking_pr_auc_ci_low",
    "accuracy_parity_ligand_ranking_topk_hit_rate",
    "accuracy_parity_ligand_ranking_positive_count",
    "accuracy_parity_ligand_ranking_score_col_used",
    "accuracy_parity_ligand_ranking_pr_auc_threshold",
    "accuracy_parity_ligand_ranking_pr_auc_ci_low_threshold",
    "accuracy_parity_ligand_ranking_topk_hit_rate_threshold",
    "accuracy_parity_ligand_ranking_next_required_step",
    "api_runner_profile_promotion_operator_receipt_gate_present",
    "api_runner_profile_promotion_operator_receipt_status",
    "api_runner_profile_promotion_operator_receipt_recorded",
    "api_runner_profile_promotion_operator_receipt_ready",
    "api_runner_profile_promotion_operator_receipt_readiness_status",
    "api_runner_profile_promotion_operator_receipt_profile_count",
    "api_runner_profile_promotion_operator_receipt_receipt_row_count",
    "api_runner_profile_promotion_operator_receipt_pass_row_count",
    "api_runner_profile_promotion_operator_receipt_blocked_row_count",
    "api_runner_profile_promotion_operator_receipt_blocker_count",
    "api_runner_profile_promotion_operator_receipt_blockers",
    "api_runner_profile_promotion_operator_receipt_first_blocked_profile_id",
    "api_runner_profile_promotion_operator_receipt_first_blocked_row_blocker",
    "api_runner_profile_promotion_operator_receipt_first_blocked_row_blockers",
    "api_runner_profile_promotion_operator_receipt_most_common_row_blocker",
    "api_runner_profile_promotion_operator_receipt_approval_token_required",
    "api_runner_profile_promotion_operator_receipt_operator_template_csv",
    "api_runner_profile_promotion_operator_receipt_next_required_step",
    "api_runner_profile_promotion_operator_receipt_profile_enabled_by_this_tool",
    "api_runner_profile_promotion_operator_receipt_runner_executed",
    "api_runner_profile_promotion_operator_receipt_external_state_mutated",
    "api_runner_profile_promotion_operator_receipt_fail_closed_guard_ready",
    "api_runner_profile_promotion_operator_receipt_fail_closed_guard_missing_reasons",
    "product_goal_release_blocker_fail_count",
    "product_goal_release_blocker_requirement_ids",
    "product_goal_primary_release_blocker_requirement_id",
    "product_goal_primary_release_blocker_tier",
    "product_goal_primary_release_blocker",
    "product_goal_primary_release_blocker_next_command",
    "primary_release_blocker_action_id",
    "primary_release_blocker_action_status",
    "primary_release_blocker_action_required_input",
    "primary_release_blocker_action_artifact_path",
    "primary_release_blocker_action_recommended_action",
    "product_accuracy_parity_action_count",
    "product_accuracy_parity_ligand_ranking_action_id",
    "product_accuracy_parity_ligand_ranking_action_present",
    "product_accuracy_parity_ligand_ranking_required_input",
    "product_accuracy_parity_ligand_ranking_artifact_path",
    "product_accuracy_parity_ligand_ranking_recommended_action",
    "product_accuracy_parity_scorecard_status",
    "product_accuracy_parity_ligand_ranking_action_status",
    "product_accuracy_parity_ligand_ranking_blocker_count",
    "product_accuracy_parity_ligand_ranking_blockers",
    "product_accuracy_parity_ligand_ranking_pr_auc",
    "product_accuracy_parity_ligand_ranking_pr_auc_ci_low",
    "product_accuracy_parity_ligand_ranking_topk_hit_rate",
    "product_accuracy_parity_ligand_ranking_next_required_step",
    "product_accuracy_parity_scorecard_json",
    "product_goal_completion_audit_artifact_path",
    "production_ai_checkpoint_registry_promotion_required_gate_ids",
    "production_ai_checkpoint_registry_promotion_missing_gate_ids",
    "production_ai_checkpoint_registry_promotion_missing_gate_count",
    "production_ai_checkpoint_registry_promotion_upstream_acceptance_ready",
    "production_ai_checkpoint_registry_promotion_currently_satisfied",
    "production_ai_checkpoint_actionable_operator_completion_packet_ready",
    "production_ai_checkpoint_actionable_operator_completion_artifact_id",
    "production_ai_checkpoint_actionable_operator_completion_required_fields_or_columns",
    "production_ai_checkpoint_actionable_operator_completion_diagnostic_commands",
    "production_ai_checkpoint_actionable_operator_completion_diagnostic_command_count",
    "production_ai_checkpoint_actionable_operator_completion_completion_rule",
    "production_ai_checkpoint_actionable_operator_completion_next_action",
    "commercial_readiness_handoff_bundle_status",
    "commercial_readiness_handoff_bundle_ready",
    "commercial_readiness_handoff_bundle_artifact_path",
    "commercial_readiness_handoff_bundle_artifact_reference_count",
    "commercial_readiness_handoff_bundle_local_missing_artifact_reference_count",
    "operator_intake_kit_production_ai_registry_promotion_priority_top_gate_id",
    "operator_intake_kit_production_ai_registry_promotion_priority_top_priority_bucket",
    "operator_intake_kit_production_ai_registry_promotion_priority_missing_gate_count",
    "bottleneck_briefing_production_ai_registry_promotion_priority_top_gate_id",
    "bottleneck_briefing_production_ai_registry_promotion_priority_top_priority_bucket",
    "bottleneck_briefing_production_ai_registry_promotion_priority_missing_gate_count",
    "commercial_readiness_handoff_bundle_production_ai_registry_promotion_priority_top_gate_id",
    "commercial_readiness_handoff_bundle_production_ai_registry_promotion_priority_top_priority_bucket",
    "commercial_readiness_handoff_bundle_production_ai_registry_promotion_priority_missing_gate_count",
    "production_ai_registry_promotion_priority_downstream_visibility_ready",
    "production_ai_registry_promotion_priority_downstream_missing_surfaces",
    "operator_intake_kit_full_commercial_evidence_receipt_entry_count",
    "operator_intake_kit_full_commercial_evidence_receipt_operator_input_required_count",
    "operator_intake_kit_full_commercial_evidence_receipt_current_action_required_count",
    "operator_intake_kit_full_commercial_evidence_receipt_template_required_count",
    "operator_intake_kit_full_commercial_evidence_receipt_template_present_count",
    "operator_intake_kit_full_commercial_evidence_receipt_approval_token_count",
    "operator_intake_kit_full_commercial_evidence_receipt_entry_ids",
    "operator_intake_kit_full_commercial_evidence_receipt_source_gate_statuses",
    "operator_intake_kit_full_commercial_evidence_receipt_required_inputs",
    "operator_intake_kit_full_commercial_evidence_receipt_approval_tokens",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_first_blocked_scope_blocker_id",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_first_blocked_evidence_artifact",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_first_blocked_expected_evidence_status",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_first_blocked_observed_evidence_status",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_first_blocked_missing_true_fields",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_first_blocked_row_blockers",
    "operator_intake_kit_product_goal_scope_breadth_evidence_receipt_most_common_row_blocker",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_blocker_id",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_evidence_artifact",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_expected_evidence_status",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_observed_evidence_status",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_missing_true_fields",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_row_blockers",
    "operator_intake_kit_product_goal_engine_refinement_claim_evidence_receipt_most_common_row_blocker",
    "bottleneck_briefing_full_commercial_evidence_receipt_entry_count",
    "bottleneck_briefing_full_commercial_evidence_receipt_operator_input_required_count",
    "bottleneck_briefing_full_commercial_evidence_receipt_current_action_required_count",
    "bottleneck_briefing_full_commercial_evidence_receipt_template_required_count",
    "bottleneck_briefing_full_commercial_evidence_receipt_template_present_count",
    "bottleneck_briefing_full_commercial_evidence_receipt_approval_token_count",
    "bottleneck_briefing_full_commercial_evidence_receipt_entry_ids",
    "bottleneck_briefing_full_commercial_evidence_receipt_source_gate_statuses",
    "bottleneck_briefing_full_commercial_evidence_receipt_required_inputs",
    "bottleneck_briefing_full_commercial_evidence_receipt_approval_tokens",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_first_blocked_scope_blocker_id",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_first_blocked_evidence_artifact",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_first_blocked_expected_evidence_status",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_first_blocked_observed_evidence_status",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_first_blocked_missing_true_fields",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_first_blocked_row_blockers",
    "bottleneck_briefing_product_goal_scope_breadth_evidence_receipt_most_common_row_blocker",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_blocker_id",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_evidence_artifact",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_expected_evidence_status",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_observed_evidence_status",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_missing_true_fields",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_first_blocked_row_blockers",
    "bottleneck_briefing_product_goal_engine_refinement_claim_evidence_receipt_most_common_row_blocker",
    "production_ai_registry_promotion_operator_receipt_status",
    "production_ai_registry_promotion_operator_receipt_ready",
    "production_ai_registry_promotion_operator_receipt_artifact",
    "production_ai_registry_promotion_operator_receipt_csv",
    "production_ai_registry_promotion_operator_receipt_approval_token_required",
    "production_ai_registry_promotion_operator_receipt_first_blocked_row_blocker",
    "production_ai_registry_promotion_operator_receipt_observed_registry_default_residual_mode",
    "production_ai_registry_promotion_operator_receipt_observed_registry_trained_model_checkpoint_count",
    "production_ai_registry_promotion_operator_receipt_observed_checkpoint_registry_promotion_currently_satisfied",
    "production_ai_registry_promotion_operator_receipt_observed_checkpoint_registry_promotion_missing_gate_ids",
    "production_ai_registry_promotion_priority_artifact",
    "production_ai_registry_promotion_priority_status",
    "production_ai_registry_promotion_priority_packet_ready",
    "production_ai_registry_promotion_priority_registry_promotion_ready",
    "production_ai_registry_promotion_priority_operator_input_required_count",
    "production_ai_registry_promotion_priority_blocked_priority_item_count",
    "production_ai_registry_promotion_priority_missing_gate_count",
    "production_ai_registry_promotion_priority_missing_gate_ids",
    "production_ai_registry_promotion_priority_top_gate_id",
    "production_ai_registry_promotion_priority_top_priority_bucket",
    "production_ai_registry_promotion_priority_top_required_input",
    "production_ai_registry_promotion_priority_top_acceptance_artifact",
    "production_ai_registry_promotion_priority_top_verification_command",
    "production_ai_registry_promotion_priority_top_next_operator_step",
    "production_ai_registry_promotion_priority_model_promoted",
    "production_ai_registry_promotion_priority_customer_facing_mutation_enabled",
    "production_ai_registry_promotion_priority_external_state_mutated",
    "cameo_official_result_fetch_preflight_status",
    "cameo_official_result_fetch_preflight_ready",
    "cameo_official_result_fetch_preflight_artifact_path",
    "cameo_official_result_fetch_preflight_operator_template_csv",
    "cameo_official_result_fetch_preflight_operator_intake_csv",
    "cameo_official_result_fetch_preflight_kit_template_path",
    "cameo_official_result_fetch_preflight_approval_token_required",
    "cameo_official_result_fetch_preflight_kit_status",
    "cameo_official_result_fetch_preflight_intake_link_ready",
    "cameo_official_result_fetch_preflight_intake_link_missing_reasons",
    "cameo_official_result_fetch_preflight_intake_source_gate_status",
    "cameo_official_result_fetch_preflight_operator_fetch_csv_present",
    "cameo_official_result_fetch_preflight_authorized_for_separate_operator_fetch",
    "cameo_official_result_fetch_preflight_network_request_opened",
    "cameo_official_result_fetch_preflight_official_results_fetched",
    "cameo_official_result_fetch_preflight_native_local_accuracy_used",
    "cameo_official_result_fetch_preflight_external_state_mutated",
    "cameo_official_result_fetch_preflight_blocker_count",
    "cameo_official_result_fetch_preflight_blockers",
    "product_rollout_execution_smoke_receipt_status",
    "product_rollout_execution_smoke_receipt_ready",
    "product_rollout_execution_smoke_receipt_artifact_path",
    "product_rollout_execution_smoke_receipt_receipt_csv",
    "product_rollout_execution_smoke_receipt_receipt_csv_present",
    "product_rollout_execution_smoke_receipt_receipt_row_count",
    "product_rollout_execution_smoke_receipt_ready_receipt_row_count",
    "product_rollout_execution_smoke_receipt_target_environment",
    "product_rollout_execution_smoke_receipt_source_rollout_execution_readiness_status",
    "product_rollout_execution_smoke_receipt_source_authorized_for_separate_operator_execution",
    "product_rollout_execution_smoke_receipt_source_rollout_executed",
    "product_rollout_execution_smoke_receipt_rollout_executed",
    "product_rollout_execution_smoke_receipt_external_state_mutated",
    "product_rollout_execution_smoke_receipt_image_pushed",
    "product_rollout_execution_smoke_receipt_service_restarted",
    "product_rollout_execution_smoke_receipt_pager_provider_contacted",
    "product_rollout_execution_smoke_receipt_ingress_certificate_verified_live",
    "product_rollout_execution_smoke_receipt_blocker_count",
    "product_rollout_execution_smoke_receipt_blockers",
    "product_rollout_execution_smoke_receipt_next_required_step",
    "product_rollout_execution_smoke_receipt_operator_receipt_guard_ready",
    "product_rollout_execution_smoke_receipt_operator_receipt_guard_missing_reasons",
    "product_launch_r4_preflight_status",
    "product_launch_r4_preflight_ready",
    "product_launch_r4_preflight_artifact_path",
    "product_launch_r4_preflight_authorized_for_r4_confirmation",
    "product_launch_r4_preflight_authorized_for_external_mutation",
    "product_launch_r4_preflight_launch_executed",
    "product_launch_r4_preflight_external_state_mutated",
    "product_launch_r4_preflight_check_count",
    "product_launch_r4_preflight_pass_count",
    "product_launch_r4_preflight_blocker_count",
    "product_launch_r4_preflight_blocked_check_ids",
    "product_launch_r4_preflight_required_r4_fields",
    "product_launch_r4_preflight_required_rollout_tokens",
    "product_launch_r4_preflight_source_api_customer_flow_status",
    "product_launch_r4_preflight_source_rollout_execution_status",
    "product_launch_r4_preflight_source_release_bundle_status",
    "product_launch_r4_preflight_source_commercial_independence_status",
    "product_launch_r4_preflight_source_license_decision_status",
    "product_launch_r4_preflight_source_third_party_license_status",
    "product_launch_r4_preflight_source_engine_refinement_status",
    "product_launch_r4_preflight_engine_refinement_claim_evidence_receipt_status",
    "product_launch_r4_preflight_engine_refinement_claim_evidence_receipt_ready",
    "product_launch_r4_preflight_engine_refinement_claim_evidence_receipt_blocked_row_count",
    "product_launch_r4_preflight_engine_refinement_claim_evidence_receipt_csv",
    "product_launch_r4_preflight_engine_refinement_claim_promotion_action_row_count",
    "product_launch_r4_preflight_next_required_step",
    "product_launch_r4_preflight_fail_closed_guard_ready",
    "product_launch_r4_preflight_fail_closed_guard_missing_reasons",
    "deploy_ops_legal_gap_closure_status",
    "deploy_ops_legal_gap_closure_complete",
    "deploy_ops_legal_gap_closure_artifact_path",
    "deploy_ops_legal_gap_closure_all_gaps_closed",
    "deploy_ops_legal_gap_closure_gap_count",
    "deploy_ops_legal_gap_closure_closed_gap_count",
    "deploy_ops_legal_gap_closure_open_gap_count",
    "deploy_ops_legal_gap_closure_closed_gap_ids",
    "deploy_ops_legal_gap_closure_open_gap_ids",
    "deploy_ops_legal_gap_closure_current_primary_open_gap_id",
    "deploy_ops_legal_gap_closure_current_next_action",
    "deploy_ops_legal_gap_closure_rollout_execution_readiness_ready",
    "deploy_ops_legal_gap_closure_rollout_smoke_receipt_status",
    "deploy_ops_legal_gap_closure_rollout_smoke_receipt_ready",
    "deploy_ops_legal_gap_closure_rollout_executed",
    "deploy_ops_legal_gap_closure_rollout_smoke_external_state_mutated",
    "deploy_ops_legal_gap_closure_rollout_smoke_pager_provider_contacted",
    "deploy_ops_legal_gap_closure_rollout_smoke_ingress_certificate_verified_live",
    "deploy_ops_legal_gap_closure_pager_provider_contacted",
    "deploy_ops_legal_gap_closure_ingress_certificate_verified_live",
    "deploy_ops_legal_gap_closure_legal_advice_provided",
    "deploy_ops_legal_gap_closure_external_state_mutated",
    "deploy_ops_legal_gap_closure_boundary_guard_ready",
    "deploy_ops_legal_gap_closure_boundary_guard_missing_reasons",
    "self_hosted_license_distribution_audit_gate_present",
    "self_hosted_license_distribution_audit_status",
    "self_hosted_license_distribution_audit_recorded",
    "self_hosted_license_distribution_audit_product_license_path",
    "self_hosted_license_distribution_audit_approved_license_text_source",
    "self_hosted_license_distribution_audit_product_license_hash_matches_approved_source",
    "self_hosted_license_distribution_audit_spdx_license_id",
    "self_hosted_license_distribution_audit_copyright_holder",
    "self_hosted_license_distribution_audit_hard_blocker_count",
    "self_hosted_license_distribution_audit_operator_review_item_count",
    "self_hosted_license_distribution_audit_third_party_dual_license_assets",
    "self_hosted_license_distribution_audit_third_party_license_review_gate_status",
    "self_hosted_license_distribution_audit_third_party_license_review_gate_ready",
    "self_hosted_license_distribution_audit_third_party_license_review_gate_blocker_count",
    "self_hosted_license_distribution_audit_viewer_third_party_notice_path",
    "self_hosted_license_distribution_audit_legal_advice_provided",
    "self_hosted_license_distribution_audit_external_state_mutated",
    "self_hosted_license_distribution_audit_boundary_guard_ready",
    "self_hosted_license_distribution_audit_boundary_guard_missing_reasons",
    "third_party_license_review_gate_present",
    "third_party_license_review_gate_status",
    "third_party_license_review_gate_recorded",
    "third_party_license_review_gate_ready",
    "third_party_license_review_gate_review_csv",
    "third_party_license_review_gate_review_csv_present",
    "third_party_license_review_gate_operator_template_csv",
    "third_party_license_review_gate_approval_token_required",
    "third_party_license_review_gate_review_row_count",
    "third_party_license_review_gate_expected_review_asset_count",
    "third_party_license_review_gate_approved_review_asset_count",
    "third_party_license_review_gate_missing_review_asset_count",
    "third_party_license_review_gate_deferred_review_asset_count",
    "third_party_license_review_gate_blocker_count",
    "third_party_license_review_gate_approved_assets",
    "third_party_license_review_gate_allowed_license_paths",
    "third_party_license_review_gate_source_license_audit_status",
    "third_party_license_review_gate_source_hard_blocker_count",
    "third_party_license_review_gate_source_operator_review_item_count",
    "third_party_license_review_gate_asset_modified",
    "third_party_license_review_gate_legal_advice_provided",
    "third_party_license_review_gate_external_state_mutated",
    "third_party_license_review_gate_boundary_guard_ready",
    "third_party_license_review_gate_boundary_guard_missing_reasons",
    "product_release_bundle_status",
    "product_release_bundle_ready",
    "product_release_bundle_artifact_path",
    "product_release_bundle_release_id",
    "product_release_bundle_bundle_version",
    "product_release_bundle_artifact_count",
    "product_release_bundle_check_count",
    "product_release_bundle_pass_count",
    "product_release_bundle_blocker_count",
    "product_release_bundle_failed_check_ids",
    "product_release_bundle_operator_policy_status",
    "product_release_bundle_operator_policy_approval_tokens_required",
    "product_release_bundle_operator_policy_must_review_fields",
    "product_release_bundle_operator_policy_required_before_execution",
    "product_release_bundle_operator_policy_external_state_mutation_allowed",
    "product_release_bundle_operator_review_guard_ready",
    "product_release_bundle_operator_review_guard_missing_reasons",
    "product_scope_breadth_evidence_priority_status",
    "product_scope_breadth_evidence_priority_packet_ready",
    "product_scope_breadth_evidence_priority_artifact_path",
    "product_scope_breadth_evidence_priority_queue_item_count",
    "product_scope_breadth_evidence_priority_open_item_count",
    "product_scope_breadth_evidence_priority_local_crosscheck_candidate_count",
    "product_scope_breadth_evidence_priority_scientific_evidence_request_count",
    "product_scope_breadth_evidence_priority_review_only_keep_blocked_count",
    "product_scope_breadth_evidence_priority_top_item_id",
    "product_scope_breadth_evidence_priority_top_domain",
    "product_scope_breadth_evidence_priority_top_bucket",
    "product_scope_breadth_evidence_priority_top_target_id",
    "product_scope_breadth_evidence_priority_top_target_promotion_status",
    "product_scope_breadth_evidence_priority_top_required_evidence_type",
    "product_scope_breadth_evidence_priority_top_review_template_artifact",
    "product_scope_breadth_evidence_priority_top_apply_gate_artifact",
    "product_scope_breadth_evidence_priority_top_next_step",
    "product_scope_breadth_evidence_priority_receipt_status",
    "product_scope_breadth_evidence_priority_receipt_ready",
    "product_scope_breadth_evidence_priority_receipt_csv",
    "product_scope_breadth_evidence_priority_receipt_row_count",
    "product_scope_breadth_evidence_priority_receipt_blocked_row_count",
    "product_scope_breadth_evidence_priority_receipt_operator_review_surface_ready_count",
    "product_scope_breadth_evidence_priority_receipt_operator_review_surface_blocked_count",
    "product_scope_breadth_evidence_priority_receipt_manual_field_pending_count",
    "product_scope_breadth_evidence_priority_receipt_evidence_artifact_pending_count",
    "product_scope_breadth_evidence_priority_receipt_claim_ready_pending_count",
    "product_scope_breadth_evidence_priority_receipt_reviewer_pending_count",
    "product_scope_breadth_evidence_priority_receipt_reviewed_at_utc_pending_count",
    "product_scope_breadth_evidence_priority_receipt_license_ok_pending_count",
    "product_scope_breadth_evidence_priority_receipt_approval_token_pending_count",
    "product_scope_breadth_evidence_priority_receipt_first_blocked_scope_blocker_id",
    "product_scope_breadth_evidence_priority_receipt_first_blocked_evidence_artifact",
    "product_scope_breadth_evidence_priority_receipt_first_blocked_expected_evidence_status",
    "product_scope_breadth_evidence_priority_receipt_first_blocked_observed_evidence_status",
    "product_scope_breadth_evidence_priority_receipt_first_blocked_missing_true_fields",
    "product_scope_breadth_evidence_priority_receipt_first_blocked_row_blockers",
    "product_scope_breadth_evidence_priority_receipt_most_common_row_blocker",
    "product_scope_breadth_evidence_priority_receipt_approval_token_required",
    "product_scope_breadth_evidence_priority_transporter_target_ready_for_promotion_count",
    "product_scope_breadth_evidence_priority_transporter_target_ready_for_promotion_ids",
    "product_scope_breadth_evidence_priority_transporter_target_blocked_for_promotion_count",
    "product_scope_breadth_evidence_priority_transporter_target_blocked_for_promotion_ids",
    "product_scope_breadth_evidence_priority_scope_promotion_allowed",
    "product_scope_breadth_evidence_priority_authoritative_apply_allowed",
    "product_scope_breadth_evidence_priority_external_state_mutated",
    "product_scope_breadth_evidence_priority_source_artifacts",
    "product_scope_breadth_evidence_priority_operator_review_guard_ready",
    "product_scope_breadth_evidence_priority_operator_review_guard_missing_reasons",
    "engine_refinement_claim_evidence_priority_status",
    "engine_refinement_claim_evidence_priority_packet_ready",
    "engine_refinement_claim_evidence_priority_artifact_path",
    "engine_refinement_claim_evidence_priority_priority_item_count",
    "engine_refinement_claim_evidence_priority_blocked_priority_item_count",
    "engine_refinement_claim_evidence_priority_operator_input_required_count",
    "engine_refinement_claim_evidence_priority_required_blocker_count",
    "engine_refinement_claim_evidence_priority_missing_required_blocker_count",
    "engine_refinement_claim_evidence_priority_missing_required_blockers",
    "engine_refinement_claim_evidence_priority_blocker_count",
    "engine_refinement_claim_evidence_priority_blockers",
    "engine_refinement_claim_evidence_priority_top_blocker_id",
    "engine_refinement_claim_evidence_priority_top_priority_bucket",
    "engine_refinement_claim_evidence_priority_top_required_input",
    "engine_refinement_claim_evidence_priority_top_acceptance_artifact",
    "engine_refinement_claim_evidence_priority_top_next_operator_step",
    "engine_refinement_claim_evidence_priority_top_verification_command",
    "engine_refinement_claim_evidence_priority_public_benchmark_status",
    "engine_refinement_claim_evidence_priority_public_benchmark_gate_ready",
    "engine_refinement_claim_evidence_priority_public_benchmark_work_order_present",
    "engine_refinement_claim_evidence_priority_public_benchmark_work_order_row_count",
    "engine_refinement_claim_evidence_priority_public_benchmark_work_order_apply_status",
    "engine_refinement_claim_evidence_priority_public_benchmark_work_order_apply_ready",
    "engine_refinement_claim_evidence_priority_public_benchmark_work_order_apply_blocked_row_count",
    "engine_refinement_priority_metric_source_payload_receipt_present",
    "engine_refinement_priority_metric_source_payload_receipt_ready",
    "engine_refinement_priority_metric_source_payload_receipt_status",
    "engine_refinement_priority_metric_source_payload_receipt_csv",
    "engine_refinement_priority_metric_source_payload_receipt_blocked_row_count",
    "engine_refinement_priority_metric_source_payload_receipt_first_blocked_template_id",
    "engine_refinement_priority_metric_source_payload_receipt_most_common_row_blocker",
    "engine_refinement_priority_metric_source_payload_receipt_approval_token_required",
    "engine_refinement_priority_planned_metric_source_payload_count",
    "engine_refinement_priority_existing_metric_source_payload_count",
    "engine_refinement_priority_required_metric_source_payloads",
    "engine_refinement_claim_evidence_priority_claim_evidence_receipt_status",
    "engine_refinement_claim_evidence_priority_claim_evidence_receipt_ready",
    "engine_refinement_claim_evidence_priority_claim_promotion_allowed",
    "engine_refinement_claim_evidence_priority_approval_token_required",
    "engine_refinement_claim_evidence_priority_approval_token_count",
    "engine_refinement_claim_evidence_priority_external_state_mutated",
    "engine_refinement_claim_evidence_priority_source_artifacts",
    "engine_refinement_claim_evidence_priority_operator_review_guard_ready",
    "engine_refinement_claim_evidence_priority_operator_review_guard_missing_reasons",
    "refine_tier_public_benchmark_work_order_apply_write_guard_ready",
    "refine_tier_public_benchmark_work_order_apply_write_guard_missing_reasons",
    "product_scope_breadth_evidence_receipt_status",
    "product_scope_breadth_evidence_receipt_ready",
    "product_scope_breadth_evidence_receipt_artifact_path",
    "product_scope_breadth_evidence_receipt_csv",
    "product_scope_breadth_evidence_receipt_csv_present",
    "product_scope_breadth_evidence_receipt_approval_token_required",
    "product_scope_breadth_evidence_receipt_receipt_row_count",
    "product_scope_breadth_evidence_receipt_pass_row_count",
    "product_scope_breadth_evidence_receipt_blocked_row_count",
    "product_scope_breadth_evidence_receipt_blocker_count",
    "product_scope_breadth_evidence_receipt_evidence_artifact_present_count",
    "product_scope_breadth_evidence_receipt_evidence_status_verified_count",
    "product_scope_breadth_evidence_receipt_first_blocked_scope_blocker_id",
    "product_scope_breadth_evidence_receipt_first_blocked_evidence_artifact",
    "product_scope_breadth_evidence_receipt_first_blocked_expected_evidence_status",
    "product_scope_breadth_evidence_receipt_first_blocked_observed_evidence_status",
    "product_scope_breadth_evidence_receipt_first_blocked_missing_true_fields",
    "product_scope_breadth_evidence_receipt_first_blocked_row_blockers",
    "product_scope_breadth_evidence_receipt_most_common_row_blocker",
    "product_scope_breadth_evidence_receipt_required_blocker_count",
    "product_scope_breadth_evidence_receipt_required_blockers",
    "product_scope_breadth_evidence_receipt_next_required_step",
    "product_scope_breadth_evidence_receipt_external_state_mutated",
    "engine_refinement_claim_evidence_receipt_status",
    "engine_refinement_claim_evidence_receipt_ready",
    "engine_refinement_claim_evidence_receipt_artifact_path",
    "engine_refinement_claim_evidence_receipt_csv",
    "engine_refinement_claim_evidence_receipt_csv_present",
    "engine_refinement_claim_evidence_receipt_approval_token_required",
    "engine_refinement_claim_evidence_receipt_receipt_row_count",
    "engine_refinement_claim_evidence_receipt_pass_row_count",
    "engine_refinement_claim_evidence_receipt_blocked_row_count",
    "engine_refinement_claim_evidence_receipt_blocker_count",
    "engine_refinement_claim_evidence_receipt_evidence_artifact_present_count",
    "engine_refinement_claim_evidence_receipt_evidence_status_verified_count",
    "engine_refinement_claim_evidence_receipt_first_blocked_blocker_id",
    "engine_refinement_claim_evidence_receipt_first_blocked_evidence_artifact",
    "engine_refinement_claim_evidence_receipt_first_blocked_expected_evidence_status",
    "engine_refinement_claim_evidence_receipt_first_blocked_observed_evidence_status",
    "engine_refinement_claim_evidence_receipt_first_blocked_missing_true_fields",
    "engine_refinement_claim_evidence_receipt_first_blocked_row_blockers",
    "engine_refinement_claim_evidence_receipt_most_common_row_blocker",
    "engine_refinement_claim_evidence_receipt_required_blocker_count",
    "engine_refinement_claim_evidence_receipt_required_blockers",
    "engine_refinement_claim_evidence_receipt_next_required_step",
    "engine_refinement_claim_evidence_receipt_external_state_mutated",
    "full_commercial_blocker_evidence_matrix_status",
    "full_commercial_blocker_evidence_matrix_ready",
    "full_commercial_blocker_evidence_matrix_artifact_path",
    "full_commercial_blocker_evidence_matrix_release_blocker_visibility_ready",
    "full_commercial_blocker_evidence_matrix_row_count",
    "full_commercial_blocker_evidence_matrix_blocked_row_count",
    "full_commercial_blocker_evidence_matrix_approval_token_count",
    "full_commercial_blocker_evidence_matrix_first_blocked_release_blocker_id",
    "full_commercial_blocker_evidence_matrix_first_blocked_evidence_row_id",
    "full_commercial_blocker_evidence_matrix_first_blocked_evidence_artifact",
    "full_commercial_blocker_evidence_matrix_first_blocked_expected_evidence_status",
    "full_commercial_blocker_evidence_matrix_first_blocked_observed_evidence_status",
    "full_commercial_blocker_evidence_matrix_first_blocked_row_blockers",
    "full_commercial_blocker_evidence_matrix_first_blocked_acceptance_artifact",
    "full_commercial_blocker_evidence_matrix_scope_receipt_most_common_row_blocker",
    "full_commercial_blocker_evidence_matrix_engine_receipt_most_common_row_blocker",
    "full_commercial_blocker_evidence_matrix_r8_blocked_row_count",
    "full_commercial_blocker_evidence_matrix_r8_first_blocked_evidence_row_id",
    "full_commercial_blocker_evidence_matrix_r8_receipt_csv",
    "full_commercial_blocker_evidence_matrix_r8_approval_token_required",
    "full_commercial_blocker_evidence_matrix_r9_blocked_row_count",
    "full_commercial_blocker_evidence_matrix_r9_first_blocked_evidence_row_id",
    "full_commercial_blocker_evidence_matrix_r9_receipt_csv",
    "full_commercial_blocker_evidence_matrix_r9_approval_token_required",
    "operator_action_count",
    "operator_intake_kit_status",
    "operator_intake_kit_release_burndown_linked_entry_count",
    "primary_action_id",
    "primary_action_status",
    "primary_action_required_input",
    "primary_action_command",
    "primary_action_recommended_action",
    "primary_action_artifact_path",
    "goal_api_surface_contract_status",
    "release_complete_vs_operator_pending_lane",
    "goal_completion_audit_goal_complete",
    "release_complete_lane_ready",
    "operator_pending_lane_ready",
}

REQUIRED_FAIL_CLOSED_FLAGS = {
    "execution_enabled",
    "action_executed",
    "delete_executed",
    "archive_executed",
    "externalize_executed",
    "upload_executed",
    "docking_results_emitted",
    "prediction_generation_enabled",
    "server_registration_mutated",
    "outbound_email_enabled",
    "external_state_mutated",
}


def _resolve(path_like: str | Path) -> Path:
    path = Path(path_like)
    return path if path.is_absolute() else ROOT / path


def _file_text(root: Path, path_like: str) -> str:
    path = root / path_like
    if not path.is_file():
        return ""
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _row(check: str, passed: bool, observed: str, required: str, artifact_path: str, reason: str) -> dict[str, Any]:
    return {
        "check": check,
        "status": "pass" if passed else "fail",
        "observed": observed,
        "required": required,
        "artifact_path": artifact_path,
        "reason": reason,
        "release_blocker": not passed,
        "execution_enabled": False,
        "action_executed": False,
        "delete_executed": False,
        "archive_executed": False,
        "externalize_executed": False,
        "upload_executed": False,
        "docking_results_emitted": False,
        "prediction_generation_enabled": False,
        "server_registration_mutated": False,
        "outbound_email_enabled": False,
        "external_state_mutated": False,
    }


def _missing_endpoint_tokens(api_text: str) -> list[str]:
    missing: list[str] = []
    for path, function_name in EXPECTED_ENDPOINTS.items():
        if f'"{path}"' not in api_text or function_name not in api_text:
            missing.append(f"GET {path}:{function_name}")
    return missing


def _missing_tokens(api_text: str, tokens: set[str]) -> list[str]:
    return sorted(token for token in tokens if token not in api_text)


def build_goal_api_surface_contract(*, root: str | Path = ".") -> dict[str, Any]:
    root_path = Path(root).resolve()
    api_text = _file_text(root_path, "api/goal.py")
    main_text = _file_text(root_path, "api/main.py")
    security_text = _file_text(root_path, "api/security.py")

    api_file_present = bool(api_text)
    router_registered = "goal_router" in main_text and "app.include_router(goal_router)" in main_text
    security_allowlist_permits_goal = "ALLOWED_PRODUCT_PREFIXES" in security_text and '"/goal"' in security_text
    missing_endpoints = _missing_endpoint_tokens(api_text)
    missing_artifact_constants = _missing_tokens(api_text, EXPECTED_ARTIFACT_CONSTANTS)
    missing_status_keys = _missing_tokens(api_text, REQUIRED_STATUS_KEYS)
    missing_full_commercial_visibility_tokens = _missing_tokens(
        api_text,
        REQUIRED_FULL_COMMERCIAL_VISIBILITY_TOKENS,
    )
    missing_fail_closed_flags = _missing_tokens(api_text, REQUIRED_FAIL_CLOSED_FLAGS)
    contract_endpoint_reads_contract = (
        "GOAL_API_SURFACE_CONTRACT_ARTIFACT" in api_text
        and "get_goal_api_contract" in api_text
        and "missing_goal_api_surface_contract" in api_text
    )

    rows = [
        _row(
            "goal_api_file_present",
            api_file_present,
            f"api/goal.py={api_file_present}",
            "api/goal.py exists",
            "api/goal.py",
            "The full objective needs a dedicated read-only API surface instead of scattered product, CAMEO, CASP17, and cleanup endpoints.",
        ),
        _row(
            "goal_router_registered",
            router_registered,
            f"goal_router_registered={router_registered}",
            "api.main imports and includes goal_router",
            "api/main.py",
            "The goal API must be mounted into the FastAPI app, not only defined as a detached module.",
        ),
        _row(
            "goal_security_allowlist_permits_goal_prefix",
            security_allowlist_permits_goal,
            f"security_allowlist_permits_goal={security_allowlist_permits_goal}",
            "api.security ALLOWED_PRODUCT_PREFIXES includes /goal",
            "api/security.py",
            "The goal API must remain reachable through the production security middleware once it is mounted.",
        ),
        _row(
            "goal_endpoints_present",
            not missing_endpoints,
            f"missing={','.join(missing_endpoints) or 'none'}",
            "all expected /goal read-only endpoints are present",
            "api/goal.py",
            "Operators need one API family for status, readiness, priority queue, Developer Preview gates, public benchmark receipts, customer shadow evidence, actions, release decision, burndown, and API contract inspection.",
        ),
        _row(
            "goal_local_artifact_sources_present",
            not missing_artifact_constants,
            f"missing={','.join(missing_artifact_constants) or 'none'}",
            "goal endpoints reference all current local goal artifacts",
            "api/goal.py",
            "The goal API must read existing local artifacts rather than infer, approve, or execute work.",
        ),
        _row(
            "goal_status_rollup_keys_present",
            not missing_status_keys,
            f"missing={','.join(missing_status_keys) or 'none'}",
            "/goal/status exposes release, operator, approval-token, protected cleanup, production AI registry diagnostics, and product/CAMEO/cleanup CLI rollup keys",
            "api/goal.py",
            "The top-level API status needs the same commercial product, CAMEO validation, and cleanup blockers that the JSON/CLI surfaces expose.",
        ),
        _row(
            "goal_full_commercial_bottleneck_visibility_present",
            not missing_full_commercial_visibility_tokens,
            f"missing={','.join(missing_full_commercial_visibility_tokens) or 'none'}",
            "/goal/status exposes R8/R9 full-commercial release blockers and commercial-readiness handoff visibility",
            "api/goal.py",
            "The goal API must not let restricted release readiness hide full-scope transporter or engine-refinement claim blockers.",
        ),
        _row(
            "goal_fail_closed_flags_present",
            not missing_fail_closed_flags,
            f"missing={','.join(missing_fail_closed_flags) or 'none'}",
            "goal endpoint responses visibly preserve disabled execution, deletion, upload, email, registration, and external-mutation flags",
            "api/goal.py",
            "The goal API must be visibly read-only and must not imply docking, submission, cleanup execution, or external mutation happened.",
        ),
        _row(
            "goal_api_contract_endpoint_reads_contract",
            contract_endpoint_reads_contract,
            f"contract_endpoint_reads_contract={contract_endpoint_reads_contract}",
            "/goal/api-contract reads runs/goal_api_surface_contract_current.json and fails closed when missing",
            "api/goal.py",
            "The goal API contract should be inspectable through the same local status surface it validates.",
        ),
    ]
    blockers = [
        {
            "code": f"{row['check']}_not_ready",
            "severity": "hard",
            "check": row["check"],
            "reason": f"{row['reason']} Observed: {row['observed']}; required: {row['required']}.",
        }
        for row in rows
        if row["status"] != "pass"
    ]
    surface_ready = not blockers
    summary = {
        "packet_type": "goal_api_surface_contract",
        "status": "goal_api_surface_contract_ready" if surface_ready else "blocked_goal_api_surface_contract",
        "surface_ready": surface_ready,
        "check_count": len(rows),
        "pass_count": sum(1 for row in rows if row["status"] == "pass"),
        "blocker_count": len(blockers),
        "expected_endpoint_count": len(EXPECTED_ENDPOINTS),
        "missing_endpoint_count": len(missing_endpoints),
        "missing_artifact_source_count": len(missing_artifact_constants),
        "missing_status_key_count": len(missing_status_keys),
        "missing_full_commercial_visibility_token_count": len(
            missing_full_commercial_visibility_tokens
        ),
        "missing_fail_closed_flag_count": len(missing_fail_closed_flags),
        "goal_api_file_present": api_file_present,
        "goal_router_registered": router_registered,
        "goal_security_allowlist_permits_goal_prefix": security_allowlist_permits_goal,
        "goal_api_contract_endpoint_present": '"/api-contract"' in api_text,
        "goal_api_contract_endpoint_reads_contract": contract_endpoint_reads_contract,
        "server_started": False,
        "execution_enabled": False,
        "action_executed": False,
        "delete_executed": False,
        "archive_executed": False,
        "externalize_executed": False,
        "upload_executed": False,
        "docking_results_emitted": False,
        "prediction_generation_enabled": False,
        "server_registration_mutated": False,
        "outbound_email_enabled": False,
        "external_state_mutated": False,
        "claim_boundary": CLAIM_BOUNDARY,
        "next_required_step": (
            "Goal API surface is ready; release still depends on product, CAMEO, cleanup, and operator approval gates."
            if surface_ready
            else "Repair failed goal API surface rows before treating the top-level API as operator-visible."
        ),
    }
    return {"summary": summary, "blockers": blockers, "rows": rows}


def _write_json(path_like: str | Path, payload: dict[str, Any]) -> None:
    path = _resolve(path_like)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def _write_markdown(path_like: str | Path, payload: dict[str, Any]) -> None:
    path = _resolve(path_like)
    s = payload["summary"]
    lines = [
        "# Goal API Surface Contract",
        "",
        f"- status: `{s['status']}`",
        f"- surface_ready: `{s['surface_ready']}`",
        f"- check_count: `{s['check_count']}`",
        f"- pass_count: `{s['pass_count']}`",
        f"- blocker_count: `{s['blocker_count']}`",
        f"- expected_endpoint_count: `{s['expected_endpoint_count']}`",
        f"- missing_endpoint_count: `{s['missing_endpoint_count']}`",
        f"- missing_artifact_source_count: `{s['missing_artifact_source_count']}`",
        f"- missing_status_key_count: `{s['missing_status_key_count']}`",
        f"- missing_full_commercial_visibility_token_count: `{s['missing_full_commercial_visibility_token_count']}`",
        f"- missing_fail_closed_flag_count: `{s['missing_fail_closed_flag_count']}`",
        f"- goal_router_registered: `{s['goal_router_registered']}`",
        f"- goal_api_contract_endpoint_present: `{s['goal_api_contract_endpoint_present']}`",
        f"- goal_api_contract_endpoint_reads_contract: `{s['goal_api_contract_endpoint_reads_contract']}`",
        f"- execution_enabled: `{s['execution_enabled']}`",
        f"- delete_executed: `{s['delete_executed']}`",
        f"- outbound_email_enabled: `{s['outbound_email_enabled']}`",
        f"- external_state_mutated: `{s['external_state_mutated']}`",
        "",
        "## Checks",
        "",
        "| check | status | observed | required | artifact | reason |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in payload["rows"]:
        lines.append(
            f"| `{row['check']}` | `{row['status']}` | `{row['observed']}` | "
            f"`{row['required']}` | `{row['artifact_path']}` | {row['reason']} |"
        )
    lines.extend(["", "## Blockers", ""])
    if payload["blockers"]:
        lines.extend(f"- `{blocker['code']}`: {blocker['reason']}" for blocker in payload["blockers"])
    else:
        lines.append("- none")
    lines.extend(["", "## Claim Boundary", "", s["claim_boundary"], "", "## Next Step", "", f"- {s['next_required_step']}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a goal API surface contract without starting the API server.")
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--out-json", default=DEFAULT_OUT_JSON)
    parser.add_argument("--out-csv", default=DEFAULT_OUT_CSV)
    parser.add_argument("--out-md", default=DEFAULT_OUT_MD)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    payload = build_goal_api_surface_contract(root=args.root)
    _write_json(args.out_json, payload)
    write_csv_rows(_resolve(args.out_csv), payload["rows"])
    _write_markdown(args.out_md, payload)


if __name__ == "__main__":
    main()
