"""Independent Engine v2 physics, registry, and composition contracts."""

from betelgeuze_engine_v2.physics.composition import (
    EnergyCompositionResult,
    EnergyTermResult,
    IndependentPhysicsProvider,
    compose_energy_terms,
)
from betelgeuze_engine_v2.parameter_source_provenance import (
    PARAMETER_SOURCE_PROVENANCE_PROFILE_ID,
    PARAMETER_SOURCE_PROVENANCE_SCHEMA_ID,
    PARAMETER_SOURCE_REVIEW_STATUS,
    ParameterSourceProvenanceError,
    ParameterSourceProvenanceSnapshot,
    parameter_source_provenance_document,
    require_parameter_source_provenance_document,
    reviewed_parameter_source_provenance,
    verify_parameter_source_review_files,
)
from betelgeuze_engine_v2.physics.projection import (
    MAX_FIXED_PROJECTION_RANK,
    ProjectionDiagnostics,
    ProjectionRankError,
    fixed_rank_orthogonal_complement,
    fixed_rank_projection_adjoint,
    local_normal_projection,
    project_rigid_body_forces,
)
from betelgeuze_engine_v2.physics.reference_forcefield import (
    ReferenceForceFieldProvider,
    ReferencePhysicsApplicabilityError,
    ReferencePhysicsEvaluation,
    evaluate_reference_force_field,
)
from betelgeuze_engine_v2.physics.reference_parameters import (
    COULOMB_KCAL_ANGSTROM_PER_MOL_E2,
    REFERENCE_PARAMETER_SCHEMA_ID,
    AtomNonbondedParameter,
    HarmonicAngleParameter,
    HarmonicBondParameter,
    PairScalingParameter,
    PeriodicTorsionParameter,
    ReferenceApplicabilityDomain,
    ReferenceForceFieldParameters,
    ReferenceParameterError,
)
from betelgeuze_engine_v2.physics.registry import (
    MAX_REGISTERED_PHYSICS_TERMS,
    IndependentPhysicsTerm,
    PhysicsRegistryEvaluation,
    PhysicsTermRegistry,
    PhysicsTermRegistryError,
    PhysicsTermRow,
    sum_validated_physics_terms,
)

__all__ = [
    "COULOMB_KCAL_ANGSTROM_PER_MOL_E2",
    "REFERENCE_PARAMETER_SCHEMA_ID",
    "AtomNonbondedParameter",
    "EnergyCompositionResult",
    "EnergyTermResult",
    "HarmonicAngleParameter",
    "HarmonicBondParameter",
    "IndependentPhysicsProvider",
    "IndependentPhysicsTerm",
    "MAX_FIXED_PROJECTION_RANK",
    "MAX_REGISTERED_PHYSICS_TERMS",
    "PARAMETER_SOURCE_PROVENANCE_PROFILE_ID",
    "PARAMETER_SOURCE_PROVENANCE_SCHEMA_ID",
    "PARAMETER_SOURCE_REVIEW_STATUS",
    "PairScalingParameter",
    "ParameterSourceProvenanceError",
    "ParameterSourceProvenanceSnapshot",
    "PeriodicTorsionParameter",
    "PhysicsRegistryEvaluation",
    "PhysicsTermRegistry",
    "PhysicsTermRegistryError",
    "PhysicsTermRow",
    "ProjectionDiagnostics",
    "ProjectionRankError",
    "ReferenceApplicabilityDomain",
    "ReferenceForceFieldParameters",
    "ReferenceForceFieldProvider",
    "ReferenceParameterError",
    "ReferencePhysicsApplicabilityError",
    "ReferencePhysicsEvaluation",
    "compose_energy_terms",
    "evaluate_reference_force_field",
    "fixed_rank_orthogonal_complement",
    "fixed_rank_projection_adjoint",
    "local_normal_projection",
    "parameter_source_provenance_document",
    "project_rigid_body_forces",
    "require_parameter_source_provenance_document",
    "reviewed_parameter_source_provenance",
    "sum_validated_physics_terms",
    "verify_parameter_source_review_files",
]
