[package]
name = "betelgeuze-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish = false
links = "betelgeuze_engine"
build = "build.rs"

[dependencies]
betelgeuze-cpu-kernel = { path = "../cpu-kernel" }

[build-dependencies]
cc = "1.2"
