[package]
name = "betelgeuze-cpu-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
betelgeuze-docking-search = { path = "../betelgeuze-docking-search" }
libm = { version = "=0.2.16", default-features = false }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
